### ISSUE TITLE
Validation are not applied properly for the existing records in the editable grid.

### ISSUE THREAD

**Issue by authorcode** [kendo-labs/breeze-kendo#7]
Hi,

I have created the model with the my defined validation in kendo-breeze.js file:

```
try {
            if (this.kendoValidation) {
                // debugger;
                for (var p in model.fields) {
                    this.kendoValidation.forEach(function (v) {
                        if (p == v.kField) {
                            model.fields[p]["validation"] = v.validation;
                        }
                    });
                }
            }
        }
        catch (ex) {
            console.error(ex);
        }
```

I pass the this.kendoValidation from my controller.

Its working great with the 'Add new record' but when I edit the existing record then nothing happen.

I am using kendo + AngularJS + Breeze.

If you have any idea please suggest me.

thanks

**Comment by rondefreitas** [comment]
I had some issues with Kendo, breeze and angular together as well.

Please try the latest changes from my fork and let me know how it works out for you.
https://github.com/rdefreitas/breeze-kendo

**Comment by authorcode** [comment]
Thank you.

I will check this later today and let you know.

But If I need to apply some my custom validation then where we need to define the my custom validation.
like as:
http://demos.telerik.com/kendo-ui/grid/editing-custom-validation

can you please review and suggest me.

**Comment by authorcode** [comment]
Hi rdefreitas 

It seems my problem has been resolved.

I made changes in kendo-breeze according to your suggestion to resolve the issue with the existing records. 
For the custom validation, I have made changes according to my first post.

thanks
